// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jrp3GHYXUJEeB3nTX7mUZFRZvkkRna4',
    appId: '1:521606021293:web:your-web-app-id',
    messagingSenderId: '521606021293',
    projectId: 'attachmates',
    authDomain: 'attachmates.firebaseapp.com',
    storageBucket: 'attachmates.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jrp3GHYXUJEeB3nTX7mUZFRZvkkRna4',
    appId: '1:521606021293:android:15a90ecdd2470e3dd30624',
    messagingSenderId: '521606021293',
    projectId: 'attachmates',
    storageBucket: 'attachmates.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYq42bBQFTF1Y487n58netz1R9CG5Zyjk',
    appId: '1:521606021293:ios:1dfa12c2add6c759d30624',
    messagingSenderId: '521606021293',
    projectId: 'attachmates',
    storageBucket: 'attachmates.firebasestorage.app',
    iosBundleId: 'com.it09.attachmates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYq42bBQFTF1Y487n58netz1R9CG5Zyjk',
    appId: '1:521606021293:ios:1dfa12c2add6c759d30624',
    messagingSenderId: '521606021293',
    projectId: 'attachmates',
    storageBucket: 'attachmates.firebasestorage.app',
    iosBundleId: 'com.it09.attachmates',
  );
}
